---
# tasks file for db-tier

- name: Install postgres
  yum:
    name: "{{ packages }}"
    state: latest
  notify:
    - initialize postgres
    - initialize postgres some more
    - start postgres
...
